Library/Pages/Administration/Block.cshtml.cs
using Library.Domain;
using Library.Infrastructure.Business.Modules.Admin.Clients.Commands.BlockUser;
using Library.Infrastructure.Security.Policys;
using Library.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Threading.Tasks;

namespace Library.Pages.Administration
{
    [Authorize(Policy.ADMIN)]
    public class BlockModel : PageModel
    {
        private readonly IMediator mediator;

        public BlockModel(IMediator mediator)
        {
            this.mediator = mediator;
        }
        [BindProperty]
        public DateTime DateBlocking { get; set; } = SystemTime.Now();
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public UserViewModel UserViewModel { get; set; } = new UserViewModel();
        public void OnGet(int id)
        {
            Id = id;
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            if(id != 0)
            {

                await mediator.Send(new BlockUserCommand(Id)
                {
                    DateBlocking = DateBlocking
                });
                return RedirectToPage("./Index");
            }
            return BadRequest();
            
        }
    }
}

Library/Pages/Administration/Delete.cshtml.cs
using Library.Infrastructure.Business.Modules.Admin.Clients.Commands.RemoveUser;
using Library.Infrastructure.Security.Policys;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Library.Pages.Administration
{
    [Authorize(Policy.ADMIN)]
    public class DeleteModel : PageModel
    {
        private readonly IMediator mediator;

        public DeleteModel(IMediator mediator)
        {
            this.mediator = mediator;
        }
        public int Id { get; set; }

        public async Task<IActionResult> OnPostRemove(int id)
        {
            if (id != 0)
            {
                await mediator.Send(new RemoveUserCommand(id));
                return RedirectToPage("./Index");
            }
            return BadRequest();
        }
    }
}

Library/Pages/Administration/Details.cshtml.cs
using Library.Infrastructure.Business.Modules.Admin.Clients.Queries.GetUserById;
using Library.Infrastructure.Security.Policys;
using Library.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Library.Pages.Administration
{
    [Authorize(Policy.ADMIN)]
    public class DetailsModel : PageModel
    {
        private readonly IMediator mediator;

        public DetailsModel(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public int Id { get; set; }

        [BindProperty]
        public UserViewModel UserViewModel { get; set; } = new UserViewModel();
        public async Task OnGet(int id)
        {
            var user = await mediator.Send(new GetUserByIdQuery(id));
            UserViewModel.Id = user.Id;
            UserViewModel.FirstName = user.FirstName;
            UserViewModel.LastName = user.LastName;
            UserViewModel.MiddleName = user.MiddleName;
            UserViewModel.Email = user.Email;
            UserViewModel.Phone = user.Phone;
            UserViewModel.Role = user.Role;
            UserViewModel.UserName = user.UserName;
            UserViewModel.IsDetails = true;
        }
    }
}

Library/Pages/Administration/Edit.cshtml.cs
using Library.Infrastructure.Business.Modules.Admin.Clients.Commands.UpdateUser;
using Library.Infrastructure.Business.Modules.Admin.Clients.Queries.GetUserById;
using Library.Infrastructure.Security.Policys;
using Library.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace Library.Pages.Administration
{
    [Authorize(Policy.ADMIN)]
    public class EditModel : PageModel
    {
        private readonly IMediator mediator;

        public EditModel(IMediator mediator)
        {
            this.mediator = mediator;
        }
        [BindProperty]
        public int Id { get; set; }

        [BindProperty]
        public UserViewModel UserViewModel { get; set; } = new UserViewModel();

        public async Task OnGetAsync(int id)
        {
            var user = await mediator.Send(new GetUserByIdQuery(id));
            UserViewModel.Id = user.Id;
            UserViewModel.FirstName = user.FirstName;
            UserViewModel.LastName = user.LastName;
            UserViewModel.MiddleName = user.MiddleName;
            UserViewModel.Email = user.Email;
            UserViewModel.Phone = user.Phone;
            UserViewModel.Role = user.Role;
            UserViewModel.UserName = user.UserName;
            UserViewModel.StatusUser = user.StatusUser;
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            if ( id == UserViewModel.Id)
            {
                var userCommand = new UpdateUserCommand()
                {
                    Id = UserViewModel.Id.Value,
                    Email = UserViewModel.Email,
                    FirstName = UserViewModel.FirstName,
                    LastName = UserViewModel.LastName,
                    MiddleName = UserViewModel.MiddleName,
                    Password = UserViewModel.Password,
                    ConfirmPassword = UserViewModel.ConfirmPassword,
                    Phone = UserViewModel.Phone,
                    Role = UserViewModel.Role,
                    UserName = UserViewModel.UserName,
                    StatusUser = UserViewModel.StatusUser
            };
                await mediator.Send(userCommand);
                return RedirectToPage("./Index");
            }
            return BadRequest();
        }
    }
}

Library/Pages/Administration/Index.cshtml.cs
using Library.Infrastructure.Business.Modules.Admin.Clients.Commands.CreateUser;
using Library.Infrastructure.Business.Modules.Admin.Clients.Commands.RemoveUser;
using Library.Infrastructure.Business.Modules.Admin.Clients.Commands.UpdateUser;
using Library.Infrastructure.Business.Modules.Admin.Clients.Models;
using Library.Infrastructure.Business.Modules.Admin.Clients.Queries.GetAllUsers;
using Library.Infrastructure.Security.Policys;
using Library.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Library.Pages.Administration
{
    [Authorize(Policy.ADMIN)]
    public class IndexModel : PageModel
    {
        private readonly IMediator mediator;

        public IndexModel(IMediator mediator)
        {
            this.mediator = mediator;
        }


        [BindProperty]
        public UserViewModel RegistrationViewModel { get; set; }

        [BindProperty]
        public IEnumerable<UserDto> Users { get; set; }
        public async Task OnGet()
        {

            Users = await mediator.Send(new GetAllUsersQuery());
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var userCommand = new CreateUserCommand()
                {
                    ConfirmPassword = RegistrationViewModel.ConfirmPassword,
                    Email = RegistrationViewModel.Email,
                    FirstName = RegistrationViewModel.FirstName,
                    LastName = RegistrationViewModel.LastName,
                    MiddleName = RegistrationViewModel.MiddleName,
                    Password = RegistrationViewModel.Password,
                    Phone = RegistrationViewModel.Phone,
                    Role = RegistrationViewModel.Role,
                    UserName = RegistrationViewModel.UserName,
                };
                await mediator.Send(userCommand);
                return RedirectToPage("./Index");
            }
            return BadRequest();
        }




    }
}

Library/Pages/Administration/Block.cshtml
@page
@model Library.Pages.Administration.BlockModel
@{
}

<div class="row">
	<form class="col s12" method="post">
		<input type="hidden" asp-for="Id" />
		<div class="row">
			<div class="input-field1 col s12">
				<label asp-for="DateBlocking">Дата блокировки</label>
				<input asp-for="DateBlocking"  />
				<span asp-validation-for="DateBlocking" class="text-danger"></span>
			</div>
		</div>
		<div class="modal-footer right">
			<button type="submit" class="btn">Заблокировать</button>
		</div>
	</form>
</div>

@section Scripts{
<script>

	$(document).ready(function(){
		$('.datepicker').datepicker();
		console.log($('.datepicker').datepicker())
	});

</script>
}

Library/Pages/Administration/Delete.cshtml
@page
@model Library.Pages.Administration.DeleteModel
@{
}

Library/Pages/Administration/Details.cshtml
@page
@using Library.Infrastructure.Business.Interfaces
@model Library.Pages.Administration.DetailsModel
@inject ILocalizationService localizationService

<div class="row">
	<form class="col s12">
		<input type="hidden" asp-for="Id" />
		<partial name="_RegistrationPartial" model="Model.UserViewModel" />
		<div class="row">
			<div class="input-field col s12">
				<select>
					@foreach (var role in Enum.GetValues(Model.UserViewModel.Role.GetType()))
					{
						@if(Model.UserViewModel.Role.ToString() == role.ToString())
						{
							<option value="@((int) role)" selected>@localizationService[role.ToString()]</option>
							continue;
						}
						<option value="@((int) role)">@localizationService[role.ToString()]</option>
					}

				</select>
				<label>Роль</label>
			</div>
		</div>
	</form>
</div>

Library/Pages/Administration/Edit.cshtml
@page
@using Library.Infrastructure.Business.Interfaces
@model Library.Pages.Administration.EditModel
@inject ILocalizationService localizationService

<div class="row">
	<form class="col s12" method="post" >
		<input type="hidden" asp-for="Id" />
		<partial name="_RegistrationPartial" model="Model.UserViewModel" />
		<div class="row">
			<div class="input-field col s12">
				<select>
					@foreach (var role in Enum.GetValues(Model.UserViewModel.Role.GetType()))
					{
						@if (Model.UserViewModel.Role.ToString() == role.ToString())
						{
							<option value="@((int) role)" selected>@localizationService[role.ToString()]</option>
							continue;
						}
						<option value="@((int) role)">@localizationService[role.ToString()]</option>
					}

				</select>
				<label>Роль</label>
			</div>
			<div class="row">
				<div class="input-field col s12">
					<select>
						@foreach (var statusUser in Enum.GetValues(Model.UserViewModel.StatusUser.GetType()))
						{
							@if (Model.UserViewModel.StatusUser.ToString() == statusUser.ToString())
							{
								<option value="@((int) statusUser)" selected>@localizationService[statusUser.ToString()]</option>
								continue;
							}
							<option value="@((int) statusUser)">@localizationService[statusUser.ToString()]</option>
						}

					</select>
					<label>Статус пользователя</label>
				</div>
			</div>
		</div>
		<div class="modal-footer right">
			<button type="submit" class="btn">Обновить</button>
		</div>
	</form>
</div>


@section Scripts{
<script>

	$(document).ready(function(){
	  $('select').formSelect();
	});

</script>
}

Library/Pages/Administration/Index.cshtml
@page
@using Library.Infrastructure.Business.Interfaces
@model Library.Pages.Administration.IndexModel
@inject ILocalizationService localizationService
@{
	ViewData["NamePage"] = "Administrator";
}

<main class="app-content">
	<div class="app-page">

		<div>
			<div class="page-title">
				<h3>Пользователи</h3>
			</div>

			<!-- Create User Modal Structure -->
			<div id="create-user" class="modal">
				<div class="modal-content">
					<div class="row">
						<form class="col s12" method="post">
							<partial name="_RegistrationPartial" model="Model.RegistrationViewModel" />
							<div class="row">
								<div class="input-field col s12">
									<select>
										<option value="" disabled selected>Выберите роль пользователя</option>
										<option value="0">Администратор</option>
										<option value="1">Библиотекарь</option>
										<option value="2">Пользователь</option>
									</select>
									<label>Роль</label>
								</div>
							</div>
							<div class="row">
								<div class="input-field col s12">
									<select>
										<option value="0" selected>Активный</option>
										<option value="1">Заблокированный</option>
									</select>
									<label>Статус пользователя</label>
								</div>
							</div>
							<div class="modal-footer">
								<button type="submit" class="btn">Добавить</button>
							</div>
						</form>
					</div>
				</div>
			</div>

			<section>
				<button class="btn-small btn right green modal-trigger" data-target="create-user">
					<i class="material-icons" title="Добавление пользователя">add</i>
				</button>
				<table class="striped">
					<thead>
						<tr>
							<th>#</th>
							<th>Имя</th>
							<th>Фамилие</th>
							<th>Отчество</th>
							<th>Почта</th>
							<th>Телефонный номер</th>
							<th>Тип роли</th>
							<th>Статус пользователя</th>
							<th></th>
						</tr>
					</thead>

					<tbody>

						@foreach (var user in Model.Users)
						{
							<tr>
								<td>@user.Id</td>
								<td>@user.FirstName</td>
								<td>@user.LastName</td>
								<td>@user.MiddleName</td>
								<td>@user.Email</td>
								<td>@user.Phone</td>
								<td>@localizationService[user.Role.ToString()]</td>
								<td>@localizationService[user.StatusUser.ToString()]</td>
								<td>
									<div class="row">
										<form class="col s3.5" method="post">
												<button class="btn-small btn red" asp-page="Delete" asp-page-handler="Remove" asp-route-id="@user.Id">
													<i class="material-icons" title="Удаление пользователя">delete</i>
												</button>
										</form>

										<a class="btn-small btn gray" asp-page="Block" asp-route-id="@user.Id">
											<i class="material-icons" title="Блокировка пользователя">block</i>
										</a>
										<a class="btn-small btn blue" asp-page="Edit" asp-route-id="@user.Id">
											<i class="material-icons" title="Обновление пользователя">edit</i>
										</a>
										<a class="btn-small btn green" asp-page="Details" asp-route-id="@user.Id">
											<i class="material-icons" title="Подробный просмотр пользователя">details</i>
										</a>
									</div>

								</td>
							</tr>
						}
					</tbody>
				</table>
			</section>
		</div>
	</div>
</main>
@section Scripts{
<script>

	$(document).ready(function(){
	  $('select').formSelect();
	   $('.modal').modal();
	});

</script>
}